### ISSUE TITLE
Failed to import video, please try again

### ISSUE THREAD

**Issue by Bonboon229** [RuurdBijlsma/MovieMaker#3]
Don't know why this is happening, but anything I try to import invokes this error

**Comment by RuurdBijlsma** [comment]
what kind of video is it, can you open console (ctrl shift i) and show what the error is there?

**Comment by Bonboon229** [comment]
Pretty much any video, let me check console output

**Comment by Bonboon229** [comment]
![image](https://github.com/RuurdBijlsma/MovieMaker/assets/59269316/08a73cb4-b919-45a3-bd84-d44f633e462b)

**Comment by Bonboon229** [comment]
This does not look good

**Comment by Bonboon229** [comment]
Edit: Supplied my own FFMPEG and put it in the appdata/roaming/moviemaker-files folder
Worked fine after that.

**Comment by RuurdBijlsma** [comment]
🤔 I'll look into it but can't reproduce it, thx for report
